# Generated by Django 2.2 on 2021-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='/profile_img/user/default_profile.png', upload_to='profile_img/teacher/%Y/%m'),
        ),
    ]
