# Generated by Django 2.2 on 2021-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210202_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='/profile_img/user/default_profile.png', upload_to='profile_img/teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
