# Generated by Django 2.2 on 2021-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210203_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='profile_img/teacher/default_profile.png', upload_to='profile_img/user/%Y/%m', verbose_name='头像'),
        ),
    ]
