# Generated by Django 2.2 on 2021-04-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20210411_0026'),
        ('users', '0006_auto_20210411_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='是否教师'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whitch_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher', unique=True),
        ),
    ]
