# Generated by Django 2.2 on 2021-04-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210415_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='profile_img/teacher/default_profile.png', max_length=500, upload_to='profile_img/user/%Y/%m', verbose_name='头像'),
        ),
    ]
