# Generated by Django 2.2 on 2021-02-02 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=20, verbose_name='教师名称')),
                ('desc', models.TextField(verbose_name='教师简介')),
                ('profile', models.ImageField(default='/profile_img/teacher/default_profile.png', upload_to='profile_img/teacher/%Y/%m', verbose_name='头像')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('course_nums', models.ImageField(default=0, upload_to='', verbose_name='课程数')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
