# Generated by Django 2.2 on 2021-03-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210204_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='desc',
            field=models.TextField(max_length=80, verbose_name='教师简介'),
        ),
    ]
