# Generated by Django 2.2 on 2021-03-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210327_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='detail',
            field=models.TextField(default='略', verbose_name='教师详情'),
        ),
    ]
