# Generated by Django 2.2 on 2021-03-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course_nums',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='detail',
            field=models.TextField(default='略', max_length=400, verbose_name='教师详情'),
        ),
    ]
