# Generated by Django 2.2 on 2021-04-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20210327_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profile',
            new_name='profile_img',
        ),
    ]
