# Generated by Django 2.2 on 2021-04-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20210411_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(default='/profile_img/teacher/default_profile.png', max_length=500, upload_to='profile_img/teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
