# Generated by Django 2.2 on 2021-03-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavorite',
        ),
        migrations.AlterModelOptions(
            name='usercourses',
            options={'verbose_name': '用户课程', 'verbose_name_plural': '用户课程'},
        ),
    ]
