# Generated by Django 2.2 on 2021-04-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210427_2351'),
        ('operations', '0004_globalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_course',
            field=models.BooleanField(default=False, verbose_name='是否课程'),
        ),
    ]
