# Generated by Django 2.2 on 2021-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20210428_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(null=True, verbose_name='访问地址'),
        ),
    ]
