# Generated by Django 2.2 on 2021-02-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='course_img.default_img.jpg', upload_to='course_img/%Y/%m', verbose_name='课程图片'),
        ),
    ]
