# Generated by Django 2.2 on 2021-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210322_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_nums',
            field=models.IntegerField(default=0, verbose_name='章节数'),
        ),
    ]
