# Generated by Django 2.2 on 2021-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_lesson_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='abc', max_length=300, verbose_name='课程公告'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(max_length=500, verbose_name='课程详情'),
        ),
    ]
