# Generated by Django 2.2 on 2021-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210322_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='notice',
            field=models.CharField(max_length=300, verbose_name='课程公告'),
        ),
    ]
