# Generated by Django 2.2 on 2021-03-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210322_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson_nums',
        ),
    ]
