# Generated by Django 2.2 on 2021-04-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210427_2351'),
        ('courses', '0010_auto_20210427_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher', verbose_name='教师'),
        ),
    ]
