# Generated by Django 2.2 on 2021-04-18 13:48

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_remove_course_lesson_nums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0006_auto_20210411_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(default='', max_length=100, verbose_name='作业标题')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='截止时间')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='正文')),
                ('homework_num', models.IntegerField(default=0, verbose_name='提交人数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher')),
            ],
            options={
                'verbose_name': '作业任务',
                'verbose_name_plural': '作业任务',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(default='', max_length=100, verbose_name='作业标题')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='正文')),
                ('score', models.IntegerField(default=-1, verbose_name='得分')),
                ('comment', DjangoUeditor.models.UEditorField(default='', verbose_name='教师评语')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.HomeworkTask')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'managed': True,
            },
        ),
    ]
