# Generated by Django 2.2 on 2021-04-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher', verbose_name='教师'),
        ),
    ]
